### ISSUE TITLE
Can't unsubscribe a channel?

### ISSUE THREAD

**Issue by nandha-dev** [ararog/WebSocketRails-Android#5]
I Can't unsubscribe a channel...

**Comment by ararog** [comment]
Can you provide a testcase? A basic snippet of what are you doing?

**Comment by nandha-dev** [comment]
chanelName = "example";

exampleChannel = dispatcher.subscribe(chanelName);

gameChannel.bind("left", new WebSocketRailsDataCallback() {
        @Override
	public void onDataAvailable(Object data) {
		// TODO Auto-generated method stub
               if (dispatcher != null) {
			if (dispatcher.isSubscribed(chanelName)) {
				dispatcher.unsubscribe(chanelName);
			}
		}
	}
});

**Comment by nandha-dev** [comment]
````java
chanelName = "example";

exampleChannel = dispatcher.subscribe(chanelName);

gameChannel.bind("testevent", new WebSocketRailsDataCallback() {
    @Override
     public void onDataAvailable(Object data) {
        // TODO Auto-generated method stub
         if (dispatcher != null) {
              if (dispatcher.isSubscribed(chanelName)) {
                  dispatcher.unsubscribe(chanelName);
              }
         }
     }
});
````

**Comment by ararog** [comment]
@nandha-dev I just updated maven central repository and bintray's jcenter repository with version 1.0.2 of this library, can you check if you are being able to download it from your pom.xml or gradle build script? Thanks!
