### ISSUE TITLE
Could not find class 'br.net.bmobile.websocketrails.WebSocketRailsConnection'

### ISSUE THREAD

**Issue by gslopez** [ararog/WebSocketRails-Android#8]
Hi, i imported the jar file in my eclipse android project. When i debug my code, appear this message in LogCat:

Could not find class 'br.net.bmobile.websocketrails.WebSocketRailsConnection', referenced from method br.net.bmobile.websocketrails.WebSocketRailsDispatcher.<init>

Please help !

**Comment by ClarkNguyen** [comment]
same problem for me :(
do u have any solution?

**Comment by ararog** [comment]
Can you guys try the jar from maven repository?

**Comment by ClarkNguyen** [comment]
nvm, i got it working by add follow dependencies libs
- https://github.com/koush/AndroidAsync
- https://github.com/FasterXML/jackson-databind
- https://github.com/FasterXML/jackson-core
- https://github.com/FasterXML/jackson-annotations

Everything working now :D
btw: i found if u forget add INTERNET permission, it's crash with NullPointerException cause ws cant initialization, u should throw exception here in class WebSocketRailsConnection :)

>@Override
>	public void onCompleted(Exception arg0, WebSocket ws) {
>		// TODO Auto-generated method stub
>      ws.setStringCallback(this);
>      ws.setClosedCallback(this);
>
>      this.webSocket = ws;
>	}

**Comment by gslopez** [comment]
Thanks!!!
